name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout

    - name: Use Node.js
      uses: actions/setup-node
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: app

    - name: Run deploy script
      run: npm run deploy
      working-directory: app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}